---
título: digitalWrite()
categorías: [ "Funciones" ]
subCategorías: [ "E/S digitales" ]
---


//
:ext-relativo: .html

= digitalEscritura()


// COMIENZA LA SECCIÓN VISIÓN GENERAL
[#overview]
--

[float]
=== Descripción
Escribe un valor `HIGH` o `LOW` a un pin digital.

Si el pin ha sido configurado como `OUTPUT` con `pinMode()`, su voltaje se ajustará al valor correspondiente: 5V (o 3.3V en placas de 3.3V) para `HIGH`, 0V (masa) para `LOW`.
[%hardbreaks]

Si el pin está configurado como `INPUT`, `digitalWrite()` activará (`HIGH`) o desactivará (`LOW`) el pullup interno del pin de entrada. Se recomienda ajustar `pinMode()` a `INPUT_PULLUP` para habilitar la resistencia interna de pull-up. Ver el tutorial de pines digitales para más información.
[%hardbreaks]

Si no establece el `pinMode()` a `OUTPUT`, y conecta un LED a un pin, al llamar a `digitalWrite(HIGH)`, el LED puede aparecer atenuado. Sin ajustar explícitamente `pinMode()`, `digitalWrite()` habrá habilitado la resistencia interna de pull-up, que actúa como una gran resistencia limitadora de corriente.
[%hardbreaks]

[float]
=== Sintaxis
`escritura digital(pin, valor)`


[float]
=== Parámetros
`pin`: el número de pin

Valor: HIGH oLOW

[float]
=== Devuelve
Nada

--
// RESUMEN SECCIÓN TERMINA




// CÓMO USAR LA SECCIÓN COMIENZA
[#cómousar]
--

[float]
=== Código de ejemplo
// Describe en qué consiste el código de ejemplo y añade el código relevante ►►►►► ESTA SECCIÓN ES OBLIGATORIA ◄◄◄◄◄
El código convierte el pin digital 13 en una `OUTPUT` y lo conmuta alternando entre `HIGH` y `LOW` a un ritmo de un segundo.

//[fuente,arduino]
----
void setup()
{
  pinMode(13, OUTPUT); // establece el pin digital 13 como salida
}

void loop()
{
  digitalWrite(13, HIGH); // activa el pin digital 13
  delay(1000); // espera un segundo
  digitalWrite(13, LOW); // apaga el pin digital 13
  delay(1000); // espera un segundo
}
----
[%hardbreaks]

[float]
=== Notas y advertencias
Los pines de entrada analógica pueden utilizarse como pines digitales, denominados A0, A1, etc.

--
// CÓMO USAR LA SECCIÓN EXTREMOS


// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--

[float]
=== Véase también

[role="ejemplo"]
* #EXAMPLE# http://arduino.cc/es/Tutorial/DigitalPins[Tutorial: Digital Pins]

--
// VER TAMBIÉN SECCIÓN EXTREMOS


