= Reference-en
Reference-en is the repo for the Language Reference documentation of the Arduino syntax in **English**.  
All the Reference terms files are in AsciiDoc format.

Gracias por tomarte el tiempo para contribuir a contenido sobre Arduino, eso es de mucha ayuda para toda la comunidad Arduino.

== Editando y Creando Contenido
Si deseas contribuir con nuevo contenido, crea un archivo nuevo (con cualquier editor de texto o codigo) y guardalo con extension .adoc.  
No uses parentesis o cualquier otro caracter especial en el nombre del archivo.  
En https://raw.githubusercontent.com/arduino/reference-en/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-en/AsciiDoc_sample/AsciiDoc_Dictionary`] encontraras una descripcion de la sintaxis AsciiDoc. Esto incluye  Titulos, Texto, Enlaces, Imagenes, Tablas, Codigo y varios embebidos (video, diapositivas, audio y codigo). Puedes verlo https://reference.arduino.cc/reference/en/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/[aqui].

Si quieres contribuir a la guia de referencia o editar contenido existente, puedes encontrar dos plantillas en reference-en/AsciiDoc_sample/Reference_Terms:

* Usa https://raw.githubusercontent.com/arduino/reference-en/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc[`AsciiDoc_Template-Single_Entity.adoc`] (presentado https://reference.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-single_entity/[aqui]) para terminos como link:http://arduino.cc/en/Reference/AnalogWrite[analogWrite].
* Usa https://raw.githubusercontent.com/arduino/reference-en/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Parent_Of_Entities.adoc[`AsciiDoc_Template-Parent_Of_Entities.adoc`] (presentado https://reference.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/[aqui]) para grupos de funciones como link:http://arduino.cc/en/Reference/Serial[Serial].

Por favor toma nota de que cada archivo de referencia deberia incluir al menos una Descripcion, algun Codigo de Ejemplo, y enlaces a otra informacion relevante (seccion Ver Tambien). 

Si necesitas adicionar imagenes al Asciidoc por favor crea un folder llamado attachments en el mismo directorio que el archivo Asciidoc . Las imagenes se pueden grabar en los formatos SVG y PNG, tamaño maximo 200KB.

== Contribuir Contenido en Github
Si no estas familiarizado con Git puedes contribuir con contenido directamente en GitHub mediante su interfaz online. Creamos un corto tutorial para enseñarte como, https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[REVISALO!]

link:https://help.github.com/articles/editing-files-in-another-user-s-repository/[Tambien puedes seguir esta guia] (escrita por el equipo de GitHub) para aprender como editar un archivo .adoc y proponer un cambio en el mismo al equipo de Arduino.  
Cuando sugieras un cambio, por favor sigue los lineamientos descritos en los archivos plantilla de referencia.


== Enviar un pull request
Estamos contentos de que desees contribuir a la guia de referencia de Arduino: esa es la mejor manera de ayudar a la comunidad.

Si tu contribucion es adicionar o modificar codigo existente o descripciones completas, por favor siempre refierase a un problema existente o abra uno nuevo antes de contribuir. 

Tome nota que sus contribuciones a la guia de Referencia de Arduino estan bajo la licencia Creative Commons Attribution-Share Alike 3.0. vea https://creativecommons.org/licenses/by-sa/3.0/


=== Estructura de los Directorios
[source]
----
reference-en
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── AsciiDoc_Template-Dictionary.adoc
│   │   └── attachments
│   └── Reference_Terms
│       ├── AsciiDoc_Template-Parent_Of_Entities.adoc
│       ├── AsciiDoc_Template-Single_Entity.adoc
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── LICENCE.md
└── README.adoc

----

Dentro del directorio de Languaje, La estructura sigue la misma estructura que en la  link:http://arduino.cc/en/Reference/HomePage[Pagina de Referencia de Arduino]
