---
title: if...else
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= if (condición) and ==, !=, <, > (operadores de comparación)


// OVERVIEW SECTION STARTS
[#overview]
--
[float]
=== Descripción
La instrucción `if` verifica si hay una condición y ejecuta la declaración o el conjunto de declaraciones si la condición es `true`.
[%hardbreaks]

[float]
=== Sintaxis
[source,arduino]
----
if (condición)
{
  //Instrucion(es)
}
----

[float]
===Parámetros
condition: una expresión booleana (es decir, puede ser `true` o `false` ).

[float]
=== Código de ejemplo

Los corchetes pueden omitirse después de una declaración `if`. Si se hace esto, la siguiente línea (definida por el punto y coma) se convierte en la única instrucción condicional.
[%hardbreaks]

[source,arduino]
----
if (x > 120) digitalWrite(LEDpin, HIGH);

if (x > 120)
digitalWrite(LEDpin, HIGH);

if (x > 120){ digitalWrite(LEDpin, HIGH); }

if (x > 120){
  digitalWrite(LEDpin1, HIGH);
  digitalWrite(LEDpin2, HIGH);
}                                 // todas son correctas
----
[%hardbreaks]


[float]
=== Notas y advertencias
Las declaraciones que se evalúan dentro de los paréntesis requieren el uso de uno o más operadores que se muestran a continuación.[%hardbreaks]

*Operadores de comparación:*

 x == y (x es igual a y)
 x != y (x no es igual a y)
 x <  y (x es menor que y)
 x >  y (x es mayor que y)
 x <= y (x es menor o igual que y)
 x >= y (x es mayor o igual que y)


Tenga cuidado de usar accidentalmente el signo igual único (Por ejemplo `if (x = 10)` ). El signo igual único es el operador de asignación y se establece `x` en 10(pone el valor 10 en la variable `x`). En su lugar, utilice el doble signo igual (ejemplo `if (x == 10)` ), Que es el operador de comparación, y comprueba si `x` es igual a 10 o no.  El último enunciado solo es verdadero si `x` es igual a 10, pero el enunciado anterior siempre será verdadero.

Esto se debe a que C ++ evalúa la sentencia de `if (x=10)` de siguiente manera: se asigna 10 a x(recuerde que el signo igual único es el ( operador de asignación ) (http://arduino.cc/en/Reference/Assignment[assignment operator^]), por lo que ahora `x` contiene 10. Luego, el condiciona 'if' conditional evalúa 10, que siempre se evalúa como `true`, porque un número distinto de cero se evalúa como `true`. En consecuencia, `if (x = 10)` siempre evaluará como `TRUE`, que no es el resultado deseado cuando se utiliza una instrucción `if`. Además, la variable `x` se establecerá en 10, que tampoco es una acción deseada.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
