---
título: analogReference()
categorías: [ "Funciones" ]
subCategorías: [ "E/S analógicas" ]
---




//




= analogReference()




// COMIENZA LA SECCIÓN OVERVIEW
[#overview]
--


[float]
=== Descripción
Configura la tensión de referencia utilizada para la entrada analógica (es decir, el valor utilizado como tope del rango de entrada). Las opciones son:


* DEFAULT: la referencia analógica por defecto de 5 voltios (en placas Arduino de 5V) o 3.3 voltios (en placas Arduino de 3.3V)
* INTERNAL: una referencia incorporada, igual a 1,1 voltios en el ATmega168 o ATmega328P y 2,56 voltios en el ATmega8 (no disponible en el Arduino Mega)
* INTERNAL1V1: una referencia integrada de 1,1 V (sólo Arduino Mega)
* INTERNAL2V56: una referencia integrada de 2,56V (sólo Arduino Mega)
* EXTERNAL: la tensión aplicada al pin AREF (sólo de 0 a 5V) se utiliza como referencia.
[%hardbreaks]




[float]
=== Sintaxis
`analogReference(tipo)`




[float]
=== Parámetros
`type`: qué tipo de referencia usar (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56, o EXTERNAL).


[float]
=== Devuelve
Nada


--
// FIN DE LA SECCIÓN








// CÓMO USAR LA SECCIÓN COMIENZA
[#cómousar]
--


[float]
=== Notas y Advertencias
Después de cambiar la referencia analógica, las primeras lecturas de `analogRead()` pueden no ser exactas.


*¡No uses nada inferior a 0V o superior a 5V para la tensión de referencia externa en el pin AREF! Si está utilizando una referencia externa en el pin AREF, debe establecer la referencia analógica a EXTERNAL antes de llamar a `analogRead()`.* De lo contrario, se producirá un cortocircuito entre la tensión de referencia activa (generada internamente) y el pin AREF, posiblemente dañando el microcontrolador en su placa Arduino.


Alternativamente, puede conectar la tensión de referencia externa a la patilla AREF a través de una resistencia de 5K, lo que le permite cambiar entre las tensiones de referencia externa e interna. Ten en cuenta que la resistencia alterará la tensión que se utiliza como referencia porque hay una resistencia interna de 32K en el pin AREF. Los dos actúan como un divisor de tensión, por lo que, por ejemplo, 2,5V aplicado a través de la resistencia dará lugar a 2,5 * 32 / (32 + 5) = ~ 2,2V en el pin AREF.
[%hardbreaks]


--
// CÓMO USAR LA SECCIÓN EXTREMOS




// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--


[float]
=== Véase también


[role="ejemplo"]
* #EXAMPLE# http://arduino.cc/es/Tutorial/AnalogInputPins[Descripción de los pines de entrada analógica]

--
// VER TAMBIÉN SECCIÓN EXTREMOS
