---
title: "+"
title_expanded: "Adición"
categories: [ "Estructura" ]
subCategories: [ "Operadores Aritméticos" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= + Adición


// OVERVIEW SECTION STARTS
[#Resumen]
--

[float]
=== Descripción
La *adición* es una de las cuantro operaciones aritméticas  básicas. El operador `+` (mas) opera en dos operandos para producir la suma.
[%hardbreaks]


[float]
=== Sintaxis
[source,arduino]
----
suma = operando1 + operando2;
----

[float]
=== Parámetros
`suma` : variable. *Tipos de datos permitidos:* int, float, double, byte, short, long +
`operando1` : variable o constante. *Tipos de datos permitidos:* int, float, double, byte, short, long +
`operando2` : variable o constante. *Tipos de datos permitidos:* int, float, double, byte, short, long
[%hardbreaks]
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Ejemplo

[source,arduino]
----
int a = 5, b = 10, c = 0;
c = a + b; // la variable 'c' recibe el valor de 15 una vez ejecutada la instrucción
----
[%hardbreaks]

[float]
=== Notas y Advertencias
1. La adición puede desbordar si el resultado es mayor que aquel que puede guardar el tipo de dato (e.g. agregar 1 a un entero que guarda 32,767 resulta en -32,768).

2. Si uno de los operandos es de tipo float o  double, se usará matemática de punto flotante para el cálculo.

3. Si los operandos son de tipo  float / double y la variable que guarda el  resultado es de tipo entero, entonces solo se guardará la parte entera y se perderá la parte fraccionaria.

[source,arduino]
----
float a = 5.5, b = 6.6;
int c = 0;
c = a + b; // la variable 'c' solo guarda el valor 12, contrastando con el valor esperado de 12.1
----
[%hardbreaks]
--
// HOW TO USE SECTION ENDS


