---
title: "="
title_expanded: "Operador de asignación "
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---


= = Asignación (signo individual de igualdad)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Al signo individual de igualdad `=` en el lenguaje de programación C  se le llama operador de asignación. Tiene un significado diferente al de la clase de álgebra, en donde indicaba una ecuación o igualdad. El operador de asignación le dice al microcontrolador que evalue el valor o expresión a la derecha del signo igual, y lo almacene en la variable a la izquierda del signo igual.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Ejemplo



[source,arduino]
----
int sensVal;              // declara una variable de tipo entero llamada sensVal
sensVal = analogRead(0);  // guarda en SensVal el voltaje (digitalizado) de la entrada análoga del pin 0
----
[%hardbreaks]

[float]
=== Notas y precauciones
1. La variable en el lado izquierdo del operador (signo = ) necesita ser capaz de contener el valor a almacenar. Si no es del tamaño adecuado para el valor, éste será almacenado erróneamente en la variable.

2. No confundir el operador de asignación [ = ] (signo individual de igualdad) con el operador de comparación [ == ] (signo doble de igualdad), el cual evalua si dos expresiones son iguales.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver también

[role="language"]
* #LENGUAJE#  link:../../control-structure/if[if (operadores condicionales )]
* #LENGUAJE#  link:../../../variables/data-types/char[char]
* #LENGUAJE#  link:../../../variables/data-types/int[int]
* #LENGUAJE#  link:../../../variables/data-types/long[long]

--
// SEE ALSO SECTION ENDS