---
title: "/"
title_expanded: "División"
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= / División


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
La *división* es una de las cuatro operations aritméticas básicas. El operator `/` (diagonal) opera con dos operandos y produce el resultado.
[%hardbreaks]


[float]
=== Sintaxis
[source,arduino]
----
resultado = numerador / denominador;
----

[float]
=== Parámetros
`resultado` : variable. *Tipos de dato permitidos:* int, float, double, byte, short, long  +
`numerador` : variable or constante. *Tipos de dato permitidos:* int, float, double, byte, short, long  +
`denominador` : variable or constante *distinta a cero* . *Tipos de dato permitidos:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Ejemplo

[source,arduino]
----
int a = 50, b = 10, c = 0;
c = a / b; // la variable 'c' recibe el valor de 5 tras ejecutarse la instrucción
----
[%hardbreaks]

[float]
=== Notas  y precauciones 
1. Si uno de los números (operandos) es de tipo float o double, se usar matemática de punto flotante para el cálculo.

2. Si los operandos son de tipo  float / double y la variable que guarda el resultado es un integer, entonces solo la parte entera es almacenada, y la parte fraccionaria se pierde.

[source,arduino]
----
float a = 55.5, b = 6.6;
int c = 0;
c = a / b; // la variable 'c' guarda el valor de 8 en lugar del resultado esperado de 8.409
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

