---
title: "*"
title_expanded: "Multiplicacion"
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---





= * Multiplicación


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
La *multiplicación* es una de las cuatro operaciones aritméticas básicas. El operador `*` (asterisco) opera con dos operandos para producir the producto.
[%hardbreaks]


[float]
=== Sintaxis
[source,arduino]
----
producto = operando1 * operando2;
----

[float]
=== Parámetros
`producto` : variable. *Tipos de dato permitidos:* int, float, double, byte, short, long  +
`operando1` : variable o constante. *Tipos de dato permitidos:* int, float, double, byte, short, long  +
`operando2` : variable o constante. *Tipos de dato permitidos:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Ejemplo

[source,arduino]
----
int a = 5, b = 10, c = 0;
c = a * b; // la variable 'c' recibe el valor de 50 tras ejecutarse esta sentencia 
----
[%hardbreaks]

[float]
=== Notas y precauciones
1. La multiplicación puede desbordar si el resultado es mayor a lo que el tipo de dato puede almacenar.

2. Si uno de los números (operandos) es de tipo float o tipo double, se usar matemática de punto flotante para el cálculo.

3. Si uno de los operandos es de tipo float / double y la variable que recibe el producto es un integer, entonces solo pa parte entera es guardada y la parte fraccionaria se pierde.

[source,arduino]
----
float a = 5.5, b = 6.6;
int c = 0;
c = a * b; //la variable'c' recibe el valor de 36 unicamente, en contraste al product esperado de 36.3
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


