---
title: Serial.available()
---




= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Devuelve el número de bytes (caracteres) disponibles para lectura en el puerto serial. Estos son datos que acaban de llegar y están almacenados en el buffer del puerto serial (el cual admite 64 bytes). `available()` hereda de la clase Stream.
[%hardbreaks]


[float]
=== Syntax
`Serial.available()`

_Arduino Mega only:_

`Serial1.available()` +
`Serial2.available()` +
`Serial3.available()`


[float]
=== Parametros
Ninguno

[float]
=== Devuelve
Número de bytes disponibles para lectura.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[source,arduino]
----
int incomingByte = 0;	// for incoming serial data

void setup() {
	Serial.begin(9600);	// opens serial port, sets data rate to 9600 bps
}

void loop() {

	// send data only when you receive data:
	if (Serial.available() > 0) {
		// read the incoming byte:
		incomingByte = Serial.read();

		// say what you got:
		Serial.print("I received: ");
		Serial.println(incomingByte, DEC);
	}
}
----
[%hardbreaks]

*Arduino Mega example:*
[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);

}

void loop() {
  // read from port 0, send to port 1:
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, BYTE);

  }
  // read from port 1, send to port 0:
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, BYTE);
  }
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialevent[SerialEvent()] +
* #LANGUAGE# link:../../stream/streamavailable[Stream.available()]

--
// SEE ALSO SECTION ENDS
