---
title: Serial.begin()
---




= begin()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Establece la velocidad de comunicación en bits por segundo (baudios) para la transmisión de datos por el puerto serial. Para comunicar con el ordenador usar una de estas velocidades: 300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 28800, 38400, 57600, o 115200. También se pueden estableder otras velocidades, por ejemplo, para establecer comunicación sobre los pines 0 y 1 con un componente que requiera una velocidad particular.

Un segundo argumento opcional configura la cantidad de datos, la paridad y el bit de parada. El valor por defecto es de 8 bits, sin paridad y un bit de parada.
[%hardbreaks]


[float]
=== Sintaxis
`Serial.begin(speed)`
`Serial.begin(speed, config)`

_Arduino Mega only:_

`Serial1.begin(speed)` +
`Serial2.begin(speed)` +
`Serial3.begin(speed)` +
`Serial1.begin(speed, config)` +
`Serial2.begin(speed, config)` +
`Serial3.begin(speed, config)`



[float]
=== Parámetros
`speed`: en bits por segundo (baudios) - `long`

`config`: establece el tipo de dato, la paridad y el bit de paradas. Son valores validos:

`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (the default) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2` +

[float]
=== Devuelve
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
    Serial.begin(9600); // opens serial port, sets data rate to 9600 bps
}

void loop() {}
----
[%hardbreaks]

*Arduino Mega example:*
[source,arduino]
----
// Arduino Mega using all four of its Serial ports
// (Serial, Serial1, Serial2, Serial3),
// with different baud rates:

void setup(){
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Hello Computer");
  Serial1.println("Hello Serial 1");
  Serial2.println("Hello Serial 2");
  Serial3.println("Hello Serial 3");
}
void loop() {}
----
[%hardbreaks]
Gracias a Jeff Gray por el ejemplo para mega

--
// HOW TO USE SECTION ENDS
